ProxyDNS: 10.0.0.251
GFWListURL: https://github.com/Loyalsoldier/v2ray-rules-dat/raw/release/gfw.txt

DefaultDNS:
  - tls://223.5.5.5
  - tls://223.6.6.6
  - quic://223.5.5.5
  - quic://223.6.6.6
  - https://223.5.5.5/dns-query
  - https://223.6.6.6/dns-query

CustomProxyDomain:
  - ghcr.io
  - oaistatic.com
  - alpinelinux.org
  - proxmox.com
  - docker.io
  - docker.com
  - chatgpt.com
  - npmjs.org
  - mikanani.me
  - mikanime.tv
  - api.jetbrains.ai